### ISSUE TITLE
Episode 70: Data Visualization with Scott Murray

### ISSUE THREAD

**Issue by hdoggett** [jensimmons/webahead-transcripts#100]
Hello everyone!

My name is Holly, and I'm going to start transcribing Episode 70: Data Visualization with Scott Murray.

Thanks for the opportunity!

**Comment by jensimmons** [comment]
Welcome Holly. And thanks!!! 

Do ask any questions that you have. Everyone is super friendly and willing to help.

**Comment by hdoggett** [comment]
Hi everyone. I have completed the transcript. Please let me know if you should need any edits or have any questions.

**Comment by jensimmons** [comment]
Thank you Holly!!! This is published now. http://thewebahead.net/70. Fabulous!

**Comment by hdoggett** [comment]
Thanks, Jen!

I see some errors I made. Should I put them on GitHub or enter edit
requests into Drupal?

Also, my Transcript free trial ran out. Would I be able to get a license to
finish up the McGrane transcript?

**Comment by jensimmons** [comment]
You should be able to make the edits directly in Drupal. Edit the transcript and hit save. The changes will be live. Yes? 

I will buy you a license as soon as I get home. 

—
Jen Simmonshttp://thewebahead.net

twitter: @jensimmons

**Comment by hdoggett** [comment]
Yes, duh. It worked! Thanks, Jen.

**Comment by jensimmons** [comment]
Holly — you need a Transcribe license. It looks like the better way to do it is for you to pay the $20 for the 1 year, and I'll reimburse you. I can paypal you $20+a bit extra to cover the fee. What's your paypal email? Or if you don't have paypal what is another way I can send you money?

**Comment by hdoggett** [comment]
Let's hold off on this for now. I just signed up for another free trial.
