### ISSUE TITLE
Episode 113: Standing on Turtles with Husani Oakley — OUR NEXT NEW SHOW 

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/webahead-transcripts#103]
Episode has been sent off to be edited. It should be done by tomorrow night. I'll post a URL once it's done. (It'll be in a new place this time, if all goes well.)

Because of one of the sponsors, it _has_ to be published ASAP. Monday evening at the latest. 

Any takers?

**Comment by jensimmons** [comment]
Here's the show!
https://www.dropbox.com/s/f6e3th0eu26a6te/webahead113.mp3?dl=0

**Comment by jensimmons** [comment]
I published the episode because there was a deadline for a sponsor. If anyone still wants to do the transcript, that would be groovy.

**Comment by mattsugihara** [comment]
Back in the US and will start on this right away.

**Comment by jensimmons** [comment]
Excellent! Thanks Matt.

-- 
Jen Simmons
Designer & Developer Advocate at Mozilla
Host and Executive Producer of The Web Ahead
http://thewebahead.net
http://jensimmons.com
twitter: jensimmons

On February 27, 2016 at 2:57:14 PM, Matt Sugihara (notifications@github.com) wrote:

Back in the US and will start on this right away.

**Comment by mattsugihara** [comment]
Is there anything remaining on this?

**Comment by jensimmons** [comment]
Nope. It's published! Thanks. Closing...
