### ISSUE TITLE
Episode 66:  Web Components with Peter Gasston

### ISSUE THREAD

**Issue by akshaynaik404** [jensimmons/webahead-transcripts#104]
Hello everyone!

My name is Akshay, and I am going to transcribe Episode 66: Web Components with Peter Gasston.

Thanks for the opportunity.

**Comment by akshaynaik404** [comment]
Just found out transcript is already there. Srry.

**Comment by jensimmons** [comment]
Hi Akshay! Welcome. 

I'm glad you saw this episode has a transcript before working on a duplicate. 

You can find a list of the shows that still need transcripts at: http://thewebahead.net/transcripts/needed if you want to grab another one.
