### ISSUE TITLE
ep114

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/webahead-transcripts#108]
Coming soon! (Like maybe tomorrow — Friday March 4). 
Rachel Andrew was the guest, and we talked about Layout Layout Layout.

Any volunteers? I'd like to publish this show next week. 

(To be clear, the show has _not_ been edited yet, but it will be done soon. I will post a comment here with the URL once it's ready.)

**Comment by jensimmons** [comment]
Here it is!
https://www.dropbox.com/s/9i73ger3s8ny2ni/webahead114.mp3?dl=0

Anyone volunteer to transcribe by Monday evening? I'd like to publish it next week, like Tues March 8, to keep on the every-other week schedule.

**Comment by jensimmons** [comment]
Ok, I'm going to take care of this one myself. So never mind. I believe 113 is still Needs-to-Be-Done. Or 115 will be coming in a week or two.

**Comment by mattsugihara** [comment]
I'm in the middle of a final polishing pass on 113. The transcript is
basically done, just making sure I spelled everyone's name properly and
that each sentence makes sense.

Will have 113 uploaded by Monday the 14th.

> ## 

Matt Sugihara
