### ISSUE TITLE
Episode 13: Education with Dan Benjamin

### ISSUE THREAD

**Issue by eliotsykes** [jensimmons/webahead-transcripts#13]
The 1st episode of The Web Ahead I listened to! If anyone has any transcription tips or software suggestions for Mac please share.

**Comment by jensimmons** [comment]
Just wanted to note that this is still almost done, but not quite: http://thewebahead.net/13 

Transcript stops at 00:57:39 for a show that's 1:23:28.

**Comment by eliotsykes** [comment]
I'm so sorry about this! Thanks for the nudge @jensimmons. I was listening to the show this week and got an awful pang of guilt about not finishing the transcript, this has been on my todo list for a long time and I just need to put aside the time. The new site is fantastic. I'll get this finished.

**Comment by eliotsykes** [comment]
Up to 1:04:14, 0:17:41 to go!

**Comment by eliotsykes** [comment]
Temporary home for transcript https://github.com/eliotsykes/webahead-transcripts/blob/master/episode-13.html

**Comment by jensimmons** [comment]
Yay! I just approved your Drupal account Eliot. Let me know if you have any troubles getting in. Someone else was finding a potential bug in the password reset system... so tell me if you need help.

**Comment by eliotsykes** [comment]
Thanks Jen, got the email (an automated one from the CMS went to spam in case that's of use). I've not tried signing in yet, I will do in the next few days.

Episode 13 transcript up to 1:06:58, 15:02 to go

**Comment by eliotsykes** [comment]
Up to 1:11:24. The free "Transcriptions" Mac app is making this a little more productive https://itunes.apple.com/gb/app/transcriptions/id911974149?mt=12

**Comment by jensimmons** [comment]
Thanks for the tip, Eliot. I just added Transcriptions app to the list at http://thewebahead.net/help/transcripts

**Comment by eliotsykes** [comment]
Up to 1:15:45

**Comment by eliotsykes** [comment]
Up to 1:20:57

**Comment by eliotsykes** [comment]
Woo! [Finished transcription](https://github.com/eliotsykes/webahead-transcripts/blob/master/episode-13.html). I'll have some time to put it in the CMS tomorrow! :+1:

**Comment by jensimmons** [comment]
Yay!

**Comment by jensimmons** [comment]
I just noticed your account didn't have the privileges to be able to add the transcript. I just fixed that — so you are all set.

**Comment by eliotsykes** [comment]
Thanks @jensimmons! It's updated with the full transcript, asides, and potential quotes http://thewebahead.net/13

**Comment by jensimmons** [comment]
Excellent! Thanks Eliot. I just posted a quote to the episode page. It's great to know this episode is complete.
