### ISSUE TITLE
Episode 70: Data Visualization with Scott Murray

### ISSUE THREAD

**Issue by pdurbin** [jensimmons/webahead-transcripts#21]
I'm about 40 minutes it to this and really enjoying it:

The Web Ahead #70: Data Visualization with Scott Murray - http://5by5.tv/webahead/70

For this transcript, I wonder if we can embed some of the d3 examples.

Honestly, the main thing I wanted capture for now is the awesome #d3brokeandmadeart that @alignedleft mentioned: https://twitter.com/hashtag/d3brokeandmadeart . It would be great if @jensimmons would add it to the show notes. The attached image from https://twitter.com/elliz/status/467265222194253824 is fun, for example. :)

![bnwppfkcmaa_-lm](https://cloud.githubusercontent.com/assets/21006/3074568/ba227e96-e345-11e3-92a4-f57add2324f8.png)

**Comment by pdurbin** [comment]
This issue was closed but episode 70 still appears under http://thewebahead.net/transcripts/needed

**Comment by jensimmons** [comment]
Yes, we do still need a transcript for episode 70. I closed this to organize things more clearly.
