### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by jennschlick** [jensimmons/webahead-transcripts#66]
@jensimmons! Can I get user permissions to edit pages?

![all_recent_content___the_web_ahead](https://cloud.githubusercontent.com/assets/463149/6196067/aa63d53a-b3a2-11e4-86cb-0759a6c93359.png)

**Comment by jensimmons** [comment]
Should be good to go now. 



—

**Comment by jennschlick** [comment]
Works, thanks!
