### ISSUE TITLE
Transcript directions

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/webahead-transcripts#68]
@jennschlick and I have been writing up directions on how to help with transcripts. It'd be great if you could check it out and see if these make sense to you.

http://thewebahead.net/help/transcripts

Any changes, additions, places that need more info?

**Comment by jensimmons** [comment]
Katherine just pointed out to me that I'd reversed dd and dt in The Canonical Directions. Whooops! It's fixed now. So use the most recent version of http://thewebahead.net/help/transcripts

**Comment by jensimmons** [comment]
For anyone transcribing an episode that hasn't come out yet (hi @jennschlick ) you should be able to access the unpublished show and find all the show note links that have been gathered. Yes? Do you have permission to look at new unpublished episodes?

Let's add a note about this to the Help with Transcripts page.

**Comment by jlschlick** [comment]
@jensimmons Yes, I can see unpublished shows. Added a note to #6 under Post the Transcript: http://thewebahead.net/help/transcripts

**Comment by cherylcolan** [comment]
Perhaps a warning not to use Transcribe (transcribe.wreally.com) "HTML source" button when coding the definition list. All my definition list elements were stripped out when I clicked out of HTML source mode. Only paragraph elements were retained. Gotta start again. Back to Coda!

**Comment by jensimmons** [comment]
Oh no! That stinks. So sorry... ;(

I just added a note to the transcript directions.
