### ISSUE TITLE
Episode 1

### ISSUE THREAD

**Issue by ksenzee** [jensimmons/webahead-transcripts#69]
Hi! I'm peeking in from the Drupal world, which is where I know Jen from. I've been out of front-end development for a long time, and I now find myself in more of a full-stack position, where it would be useful if I had stayed up to date. So I thought I'd listen to the series from the beginning, as a way of catching up with developments in the field. And then I saw help was needed transcribing, and I like transcribing, so here I am. Starting at Episode #1 because I'm listening from the beginning anyway.

**Comment by jensimmons** [comment]
:smile:

**Comment by ksenzee** [comment]
Transcript created on the site.

**Comment by jensimmons** [comment]
Published! http://thewebahead.net/1

Thanks so much. This is terrific. :)
