### ISSUE TITLE
ep99 - Responsive Images!

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/webahead-transcripts#75]
Hiya.
Episode 99 has been edited. It's at 
http://fdlyr.co/d/webahead/cdn.5by5.tv/audio/broadcasts/webahead/2015/webahead-099.mp3

It's all about how-to do responsive images. 

/cc @jennschlick

**Comment by jensimmons** [comment]
By the way, I've been removing many of the timestamps from transcripts. Not most — but in the places where the dialog is super short and back-and-forth. You can look at ep 98 to see what I mean. 
http://thewebahead.net/98

Usually this is right at the beginning of the show, and again at the end. I think this makes the transcript more readable — to not have a timestamp on every line when the lines are just a few words long. People won't need stamps that are seconds, or one minute apart. Just having one at the beginning of the back-and-forth, and then at the beginning of when the topic changes / when the next beat starts....

Make sense?

I don't know if Jenn, it's easier for you to leave these out — or if actually leaving them out creates more work for you. I don't mind removing them when I edit the transcript, but that is a bit more work on my side... so if it's easy for you to not include these, then lets drop them. Yes? Or if it's a total pain for you, then never mind! I'm not sure how the software you are using works.

**Comment by jlschlick** [comment]
Good point. Easy to leave out timestamps on short bursts of dialogue. It just means while transcribing I'll have to think a bit more, instead of being all robotic and hitting the shortcut (F6) every time someone speaks. So, yes, doable.

**Comment by jensimmons** [comment]
Yay! I just finished the epic show notes for this one. A katrillion links! I'm glad to now have the transcript. :)

**Comment by jlschlick** [comment]
Seriously epic! Added additional links in the transcript, like Twitter/Wikipedia links for people, [an explanation of the lookahead pre-parser](http://andydavies.me/blog/2013/10/22/how-the-browser-pre-loader-makes-pages-load-faster/), and [Sara Soueidan's article](http://sarasoueidan.com/blog/svg-picture/). Also found the [flowchart](http://lists.w3.org/Archives/Public/public-respimg/2015Jan/0003.html) Jason mentioned, but maybe an earlier version and maybe on his personal Dropbox, soooo yeah.

**Comment by jensimmons** [comment]
Excellent! Yes, I've started reading the transcript to find all the links you've added, and add them to the show note list you. You get some good ones.

**Comment by jensimmons** [comment]
I was just listening to some of the show while reading the transcript (around min16). I'm really happy with how much you are cleaning up the mistakes in speech. It's really good. I hadn't realized you were leaving out so many stumbles and circular half-thoughts... but I'm really pleased. :+1:

**Comment by jlschlick** [comment]
Hey, thanks! Have been editing more heavily lately... trying to find a middle ground between readability and accuracy. I still totally fear a guest reading it and saying, "I didn't say that!"
