### ISSUE TITLE
Episode ONE HUNDRED

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/webahead-transcripts#78]
Ep100 is edited and ready to be transcribed. (I'm traveling, so I stacked a few in a row).
http://fdlyr.co/d/webahead/cdn.5by5.tv/audio/broadcasts/webahead/2015/webahead-100.mp3

**Comment by jensimmons** [comment]
cc @jennschlick 
Jenn, do you see these notices without the cc?

**Comment by jlschlick** [comment]
@jensimmons Yup. I get notifications for all conversations, I think because I'm watching the repo.

**Comment by jensimmons** [comment]
Coll, then I'll stop cc'ing you when posting a new episode. I feel like I'm "ordering" you to GET GOING! And that not my intention. ;)

**Comment by jlschlick** [comment]
Haha, no worries, it doesn't come off that way.

Transcript is done.
