### ISSUE TITLE
Episode 47

### ISSUE THREAD

**Issue by JasonNeel** [jensimmons/webahead-transcripts#79]
Been out of the game for awhile. Figured I’d jump back in with this one, since I already did the other Jen Robbins episode.

**Comment by jensimmons** [comment]
\o/

**Comment by JasonNeel** [comment]
I don't think I have the ability to assign this issue to you Jen, like the transcription instructions say. Either that, or I'm just not seeing it on my end. (Ugh, I need to get better at Github.)

But I just entered all of the info I have for this episode into the Drupal backend for you to review.

**Comment by jensimmons** [comment]
Ah, right. I should change the directions. I think only people who have full privileges to commit to this repo have the ability to assign issues (which I haven't bothered to mess with — not quite seeing the benefits. Maybe I should look at that...)

Ok. Cool! Thanks.
