### ISSUE TITLE
Episode 34: Intro to The Web Behind

### ISSUE THREAD

**Issue by mf3k** [jensimmons/webahead-transcripts#8]
i was thinking about transcribing the web behind episodes first, if that's ok. i'll start with the intro episode and work my way up.

**Comment by jensimmons** [comment]
I'd still love to see a transcript here: http://thewebahead.net/34 Interested @mf3k? Or anyone else?

**Comment by mf3k** [comment]
sorry, things derailed a _little_ on my end, but I got this. I'll make the pull request at the end of the week and start on the next **the web behind episodes** next week. again, sorry.

**Comment by jensimmons** [comment]
Excellent! And no need for being sorry. It's exciting to get momentum now. There's info on how to do transcripts at: http://thewebahead.net/help/transcripts

**Comment by mf3k** [comment]
Jen, i created an account at the web ahead website, but still need for you to approve the account so i can post this transcript. or do you want to handle this differently?

**Comment by jensimmons** [comment]
I just approved your account and made you a transcript contributor. You should be all set. Let me know if you have any questions.

**Comment by mf3k** [comment]
everything is loaded up and ready to be published. hope it's ok.

**Comment by jensimmons** [comment]
I just added `<abbr></abbr>` to the allowed HTML in the system. Great call.

**Comment by jensimmons** [comment]
I just published this transcript! Thanks so much! http://thewebahead.net/34
