### ISSUE TITLE
Episode 102 - Understanding Apple Watch with Josh Clark

### ISSUE THREAD

**Issue by jensimmons** [jensimmons/webahead-transcripts#83]
Ta da.
http://fdlyr.co/d/webahead/cdn.5by5.tv/audio/broadcasts/webahead/2015/webahead-102.mp3

Yes, that's two episodes edited today. 
101 was recorded yesterday, and will be published next week. 
102 was recorded today. It'll be published the week of April 6th (week after next).

**Comment by jlschlick** [comment]
Just finished 101. Doing this next!

**Comment by jensimmons** [comment]
:D

**Comment by jlschlick** [comment]
Done.

**Comment by jensimmons** [comment]
You are awesome. 

—
