### ISSUE TITLE
ep 105 in this episode overflow

### ISSUE THREAD

**Issue by mattsugihara** [jensimmons/webahead-transcripts#95]
It looks like extra teaser content for episode 105 is overlapping with episode 104.
<img width="711" alt="screen shot 2015-09-09 at 10 42 43 pm" src="https://cloud.githubusercontent.com/assets/166028/9780986/1fbe4d5c-5744-11e5-80a6-08afb698d922.png">

**Comment by jensimmons** [comment]
Ah, there were too many `<ul>`s wrapping the list. It should be fixed now. 

Let me know if you still see a problem.

Thanks!
